#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import plotly.express as px
import plotly.graph_objects as go

import numpy as np
from PIL import Image
import base64
import io
import pint
import struct # for binary files

import os    

import re
import json

import zipfile

from nomad.datamodel.metainfo.plot import PlotSection
from nomad.datamodel.metainfo.eln import ELNMeasurement
#from nomad.parsing.tabular import TableData
from nomad.datamodel.data import UserReference, AuthorReference
from nomad.datamodel.metainfo.eln import BasicEln
from nomad.datamodel.metainfo.basesections.v1 import ReadableIdentifiers
from nomad.datamodel.metainfo.basesections.v1 import PureSubstance
from nomad.datamodel.metainfo.basesections.v1 import PureSubstanceSection
from nomad.datamodel.metainfo.eln import ELNInstrument
from nomad.datamodel.metainfo.eln import Chemical
from nomad.datamodel.data import EntryData


from typing import (
    TYPE_CHECKING,
)
from nomad.metainfo import (
    MSection,
    Package,
    SchemaPackage,
    Quantity,
    SubSection,
    MEnum,
    Reference,
    Datetime,
    Section,
)
from nomad.datamodel.data import (
    EntryData,
    ArchiveSection,
)
from nomad.datamodel.data import (
    EntryDataCategory,
)
from nomad.metainfo.metainfo import (
    Category,
)
from nomad.units import ureg
from nomad.datamodel.metainfo.plot import (
    PlotlyFigure,
    PlotSection,
)
from nomad.config import config
# from nomad.metainfo.elasticsearch_extension import (
#     Elasticsearch,
#     material_entry_type,
#     entry_type as es_entry_type,
#     create_searchable_quantity,
# )

if TYPE_CHECKING:
    from nomad.datamodel.datamodel import (
        EntryArchive,
    )
    from structlog.stdlib import (
        BoundLogger,
    )
    
configuration = config.get_plugin_entry_point(
    'crc1415plugin.schema_packages:CRC1415SampleOverview'
)

from .schemas_measurement import MeasurementAdsorption
from .schemas_measurement import MeasurementGeneric
from .schemas_measurement import MeasurementIR
from .schemas_measurement import MeasurementRaman
from .schemas_measurement import MeasurementSEM
from .schemas_measurement import MeasurementTEM
from .schemas_measurement import MeasurementXRD


m_package = SchemaPackage(name='CRC1415 Sample ELN')


class DataFileError(Exception):
    """Custom exception for data file errors."""
    pass


class CRC1415Category(EntryDataCategory):
    """
    A category for all plugins defined in the `crc1415-plugin` plugin.
    """

    m_def = Category(label='CRC1415', categories=[EntryDataCategory])
    

class CRC1415CategoryMeasurement(EntryDataCategory):
    """
    A category for all plugins defined in the `crc1415-plugin` plugin.
    """

    m_def = Category(label='CRC1415-Measurement', categories=[EntryDataCategory])

class CRC1415Chemical(Chemical, EntryData, ArchiveSection):
    '''
    This is an example description for Chemical.
    A description can contain **markdown** markup and TeX formulas, like $\\sum\\limits_{i=0}^{n}$.
    '''
    m_def = Section(
        categories=[CRC1415CategoryMeasurement],
        label='CRC1415-Chemical',
    )
    form = Quantity(
        type=MEnum(['crystalline solid', 'powder', 'solution']),
        a_eln={
            "component": "EnumEditQuantity"
        },
    )
    cas_number = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    ec_number = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `CRC1415Chemical` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class Instrument(ELNInstrument, EntryData, ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Instrument` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class IRInstrument(Instrument, ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()


class Contributors(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    Contributors = Quantity(
        type=AuthorReference,
        a_eln={
            "component": "AuthorEditQuantity"
        },
    )









class MeasurementTGA(ELNMeasurement, PlotSection, ArchiveSection):
    '''
    Class for handling measurement of ThermoGravimetricAnalysis.
    '''
    m_def = Section(
        categories=[CRC1415CategoryMeasurement],
        label='CRC1415-Measurement-TGA',
        a_eln={
            "overview": True,
            "hide": [
                "name",
                "lab_id",
                "method",
                "samples",
                "measurement_identifiers"
            ],
            "properties": {
                "order": [
                    "tags",
                    "datetime",
                    "location",
                    "data_as_txt_file",
                    "TGA_Sample_Mass",
                    "TGA_Temperature_Start",
                    "TGA_Temperature_End",
                    "TGA_Rate",
                    "description"
                ]
            }
        },
    )
    lab_id = Quantity(
        type=str,
        a_display={
            "visible": False
        },
    )
    data_as_txt_file = Quantity(
        type=str,
        description="A reference to an uploaded Quantachrome .txt produced by the TGA instrument.",
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity",
            "label": "data as .txt file of TGA experiment"
        },
    )
    
    TGA_Rate= Quantity(
        type=np.float64,
        unit='kelvin/minute',
        description='The rate for temperature increase during the TGA, kelvin per minute.',
        a_eln=dict(component='NumberEditQuantity', label='TGA Rate', defaultDisplayUnit= 'kelvin/minute'),
    )
    
    TGA_Temperature_Start = Quantity(
        type=np.float64,
        unit='celsius',
        description='The starting temperature for the TGA, celsius.',
        a_eln=dict(component='NumberEditQuantity', label='TGA Temperature Start', defaultDisplayUnit= 'celsius'),
    )
    
    TGA_Temperature_End = Quantity(
        type=np.float64,
        unit='celsius',
        description='The ending temperature for the TGA, celsius.',
        a_eln=dict(component='NumberEditQuantity', label='TGA Temperature End', defaultDisplayUnit= 'celsius'),
    )
    
    
    TGA_Sample_Mass = Quantity(
        type=np.float64,
        unit='milligram',
        description='The mass of the sample in the TGA, milligram.',
        a_eln=dict(component='NumberEditQuantity', label='TGA Sample Mass', defaultDisplayUnit= 'milligram'),
    )
    
    TGA_Temperature = Quantity(
        type=np.float64,
        shape=["*"],
        unit='celsius',
        description='The temperature in the TGA, celsius.',
        a_eln=dict(defaultDisplayUnit = 'celsius'),
    )
    
    
    TGA_Mass_Subtrate = Quantity(
        type=np.float64,
        shape=["*"],
        unit='dimensionless',
        description='The measured mass at temperature in the TGA, given in percent.',
        a_eln=dict(defaultDisplayUnit = 'dimensionless'),
    )
    
    
    
    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger'):
        """
        The normalize function of the `MeasurementTGA` section.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        """
        
        try:
            # Check if any file is provided
            if self.data_as_txt_file:
                # Check if the file has the correct extension
                if not self.data_as_txt_file.endswith('.txt'):
                    raise DataFileError(f"The file '{self.data_as_txt_file}' must have a TGA .txt extension.")
            
                # Get the encoding
                # from chardet import detect # for Quantachrome ASiQwin text as the file has the 'Windows-1252' encoding
                # # but this can usally ignored as the only character is the Angstrom 
                
                # with archive.m_context.raw_file(self.data_as_txt_file, 'rb') as txtfile:
                #     rawdata = txtfile.read()
                #     get_encoding_type = detect(rawdata)['encoding']
                #     print(get_encoding_type)
                
                #with archive.m_context.raw_file(self.data_as_txt_file, 'r', errors='ignore') as txtfile:
                with archive.m_context.raw_file(self.data_as_txt_file, 'r', encoding='iso8859-15') as txtfile:
                    # parse the metadata
                    text = txtfile.read()
                    #print(text)
                    
                    mass = re.search(r'#SAMPLE MASS /(\w+):(\d+),(\d+)', text, re.IGNORECASE)
                    
                    if mass:
                        if len(mass.groups()) == 3:
                            # Combine them to form the complete number
                            mass_decimal = f"{mass.group(2)}.{mass.group(3)}"  # Convert to standard decimal format
                            self.TGA_Sample_Mass = ureg.Quantity(float(mass_decimal), mass.group(1).lower()) # decimal[comma]decimal, mg
                    
                    temp_range = re.search(r'#RANGE:(\d+)(°C)/([\d.]+)\((K/min)\)/(\d+)(°C)', text)
                    #print(temp_range)
                    #print(len(temp_range.groups()))
                    #print(temp_range.groups())
                    
                    if temp_range:
                        if len(temp_range.groups()) == 6: # start, degC, rate, K/min, stop, degC
                            
                            self.TGA_Temperature_Start = ureg.Quantity(float(temp_range.group(1)), temp_range.group(2))  # decimal, degC
                            
                            self.TGA_Rate = ureg.Quantity(float(temp_range.group(3)), temp_range.group(4).lower().replace('k/min', 'kelvin/minute'))  # decimal, K/min
                            
                            self.TGA_Temperature_End = ureg.Quantity(float(temp_range.group(5)), temp_range.group(6))  # decimal, degC
                    
                    # Use regex to extract the date and time: #DATE/TIME: DD.MM.YYYY HH:MM
                    time_exp = re.search(r'#DATE/TIME:(\d{1,2}\.\d{1,2}\.\d{4}\s+\d{1,2}:\d{1,2})', text)
                    #print(time_exp)
                    # Check if a match was found
                    if time_exp:
                        # Convert the unpacked data as a datetime object
                        from datetime import datetime
                        import pytz
                        exp_time = datetime.strptime(time_exp.group(1), "%d.%m.%Y %H:%M")
                        
                        local_tz = pytz.timezone('Europe/Berlin')
                        target_tz = pytz.timezone('UTC')
                        
                        exp_time = local_tz.localize(exp_time) # set to Berlin time
                        exp_time = target_tz.normalize(exp_time) #transfer to UTC
                        
                        self.datetime = exp_time
                        
                
                with archive.m_context.raw_file(self.data_as_txt_file, 'r', encoding='iso8859-15') as txtfile:
                    # Read-in the special encoded file
                    data_tga = np.loadtxt(txtfile, encoding='iso8859-15', delimiter=';', usecols=[0,3])
                    # Unpack the two columns into separate arrays
                    tga_temperature, tga_mass_percent = data_tga[:, 0], data_tga[:, 1]
                    
                    # note: percent as unit is available at pint v0.22 -> this here is v.17
                    self.TGA_Temperature = ureg.Quantity(tga_temperature, 'celsius')
                    self.TGA_Mass_Subtrate = ureg.Quantity(tga_mass_percent, 'dimensionless')
                    
                    # create plot
                    figures = []
                    
                    # Create a figure
                    fig = go.Figure()
                    
                    x_label = 'Temperature'
                    xaxis_title = 'Temperature [\u2103]'
                    
                    y_label = 'Sample Mass'
                    yaxis_title = 'Sample Mass [%]' #f'Adsorbed Volume [mmol/g] ({self.Analysis_Gas}, {self.Bath_Temperature.to('kelvin').magnitude} {self.Bath_Temperature.units:~})'
                    
                    # Add the first line with markers
                    fig.add_trace(go.Scatter(
                        x=np.array([temp.to('celsius').magnitude for temp in self.TGA_Temperature]), #self.TGA_Temperature.to('celsius').magnitude,
                        y=np.array([mass.to_base_units().magnitude for mass in self.TGA_Mass_Subtrate]), #self.TGA_Mass_Subtrate,
                        mode='lines+markers',  # 'lines+markers' to show both lines and markers
                        name='TGA',         # Name of the first line
                        line=dict(color='blue'),  # Line color
                        hovertemplate='(x: %{x}, y: %{y})<extra></extra>',  # Custom hovertemplate
                        marker=dict(size=5, symbol='circle')      # Marker size
                    ))
                    
                    
                    fig.update_layout(
                        title=f'{y_label} over {x_label}',
                        xaxis_title=xaxis_title,
                        yaxis_title=yaxis_title,
                        xaxis=dict(
                            fixedrange=False,
                        ),
                        yaxis=dict(
                            fixedrange=False,
                        ),
                        template='plotly_white',
                        showlegend=True,
                        hovermode="x unified", # provides a dashed line and finds the closest point
                    )
                    
                    # figures.append(
                    #     PlotlyFigure(
                    #         label=f'{y_label}-{x_label}',
                    #         #index=0,
                    #         figure=fig.to_plotly_json(),
                    #     ),
                    # )
                    
                    figure_json = fig.to_plotly_json()
                    figure_json['config'] = {'staticPlot': False, 'displayModeBar': True, 'scrollZoom': True, 'responsive': True, 'displaylogo': True, 'dragmode': True}
                    
                    figures.append(PlotlyFigure(label=f'{y_label}-{x_label} linear plot', figure=figure_json))
                    
                    self.figures = figures
        
        
        except Exception as e:
            logger.error('Invalid file extension for parsing.', exc_info=e)
        # In case something is odd here -> just return
        # if not self.results:
        #    return
        
        super().normalize(archive, logger)


class CVData(ArchiveSection):
    """General data section for cyclic voltammetry"""

    m_def = Section(
        label_quantity='name',
        a_eln={
            # "overview": False,
            # "hide": [
            #     "name",
            #     "lab_id",
            #     "method",
            #     "samples",
            #     "measurement_identifiers"
            # ],
            "properties": {
                "order": [
                    "name",
                    "data_as_txt_file",
                    "CV_Scanrate",
                ]
            }
        },
    )
    
    name = Quantity(
        type=str,
        #default='TestName',
        description='Name of the section or CV measurement',
        a_eln={'component': 'StringEditQuantity', 'label': 'CV: Title of the measurement'},
    )
    
    data_as_txt_file = Quantity(
        type=str,
        description="A reference to an uploaded .txt file produced by the cyclic voltammetry instrument.",
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
    
    CV_Scanrate = Quantity(
        type=np.float64,
        unit='volt/second',
        description='The scanrate used in the CV experiment, volt/second.',
        a_eln=dict(component='NumberEditQuantity', label='CV: Scanrate', defaultDisplayUnit= 'volt/second'),
    )
    
    CV_Potential = Quantity(
        type=np.float64,
        shape=["*"],
        unit='volt',
        description='The applied potential during the cyclic voltammetry experiment, volt.',
        a_eln=dict(label='CV Potential', defaultDisplayUnit= 'volt'),
    )
    
    CV_Current = Quantity(
        type=np.float64,
        shape=["*"],
        unit='milliampere',
        description='The measured current during the cyclic voltammetry experiment, milliampere',
        a_eln=dict(label='CV Current', defaultDisplayUnit= 'milliampere'),
    )

class MeasurementCV(ELNMeasurement, PlotSection, ArchiveSection):
    '''
    Class for handling measurement of cyclic voltammetry experiment.
    '''
    m_def = Section(
        categories=[CRC1415CategoryMeasurement],
        label='CRC1415-Measurement-CV',
        a_eln={
            "overview": True,
            "hide": [
                "name",
                "lab_id",
                "method",
                "samples",
                "measurement_identifiers"
            ],
            "properties": {
                "order": [
                    "tags",
                    "datetime",
                    "datetime_end",
                    "location",
                    "CV_Electrolyte",
                    "CV_Electrolyte_Concentration",
                    "CV_pH_Value",
                    "CV_Reference_Electrode",
                    "CV_Counter_Electrode_Material",
                    "CV_Working_Electrode_Material",
                    "data_as_ids_file",
                    "description"
                ]
            }
        },
        )
            
    lab_id = Quantity(
        type=str,
        a_display={
            "visible": False
        },
    )
    
    datetime_end = Quantity(
        type=Datetime,
        description='The date and time when this activity has ended.',
        a_eln=dict(component='DateTimeEditQuantity', label='Ending Time'),
    )
    
    CV_Electrolyte = Quantity(
        type=str,
        #default='TestName',
        description='The electrolytes in cyclic voltammetry facilitate ion transport, enabling electrochemical reaction measurements',
        a_eln=dict(component='EnumEditQuantity', label='CV: Electrolyte', suggestions=['KHCO3', 'KCl', 'Na2SO4']),
    )
    
    CV_Electrolyte_Concentration = Quantity(
        type=np.float64,
        unit='mol/l',
        description='The concentration of the electrolytes in cyclic voltammetry, mol/liter.',
        a_eln=dict(component='NumberEditQuantity', label='CV: Electrolyte Concentration', defaultDisplayUnit= 'mol/liter'),
    )
    
    CV_pH_Value = Quantity(
        type=np.float64,
        unit='dimensionless',
        description='The pH value in cyclic voltammetry experiment, dimensionless.',
        a_eln=dict(component='NumberEditQuantity', label='CV: pH Value', defaultDisplayUnit= 'dimensionless'),
    )
    
    CV_Reference_Electrode = Quantity(
        type=str,
        #default='TestName',
        description='The used reference electrode in the experiment.',
        a_eln=dict(component='EnumEditQuantity', label='CV: Reference Electrode', suggestions=['Ag|AgCl (3M)', 'Ag|AgCl (saturated)', 'Hg/Hg2Cl2 (saturated)', 'RHE (reversible hydrogen electrode)']),
    )
    
    CV_Counter_Electrode_Material = Quantity(
        type=str,
        #default='TestName',
        description='The material, which the counter electrode is made of.',
        a_eln=dict(component='EnumEditQuantity', label='CV: Counter Electrode Material', suggestions=['Platinum wire', 'Platinum mesh', 'Graphite', 'Gold']),
    )
    
    CV_Working_Electrode_Material = Quantity(
        type=str,
        #default='TestName',
        description='The material, which the working electrode is made of.',
        a_eln=dict(component='EnumEditQuantity', label='CV: Working Electrode Material', suggestions=['Graphite', 'Glassy carbon', 'Gold', 'Silver']),
    )
    
    
    data_as_ids_file = Quantity(
        type=str,
        description="A reference to an uploaded cyclic voltammetry .ids file produced by the CV instrument.",
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
    
    CV_data_entries = SubSection(section_def=CVData, repeats=True)
    
    
    def generate_plots(self) -> list[PlotlyFigure]:
        """
        Generate the plotly figures for the `MeasurementCV` section.

        Returns:
            list[PlotlyFigure]: The plotly figures.
        """
        figures = []
        # Create the figure
        fig = go.Figure()
        
        #for r_d_entries in self.Raman_data_entries:
        for idx, r_d_entries in enumerate(self.CV_data_entries):
            #print(f"Index {idx}/{(len(self.Raman_data_entries) - 1)}: {r_d_entries}")
            # Add line plots
            x = r_d_entries.CV_Potential.to(r_d_entries.CV_Potential.units).magnitude
            y = r_d_entries.CV_Current.to(r_d_entries.CV_Current.units).magnitude
            
            
            # Get the Viridis color scale
            viridis_colors = px.colors.sequential.Viridis
            
            color_index_line = int(idx / (len(self.CV_data_entries)-1) * (len(viridis_colors) - 1)) if len(self.CV_data_entries) > 1 else 0
            
            fig.add_trace(go.Scatter(
                x=x,
                y=y,
                mode='lines+markers',  # 'lines+markers' to show both lines and markers
                name=f'cycle: {idx}',
                line=dict(color=viridis_colors[color_index_line]), # int(idx / (len(self.Raman_data_entries)) * (len(viridis_colors) - 1))]),
                hovertemplate='(x: %{x}, y: %{y})<extra></extra>',
                marker=dict(size=5, symbol='circle')      # Marker size
            ))

        # exemply use the first entry for the units
        x_label = 'Potential'
        xaxis_title = f'{x_label} ({self.CV_data_entries[0].CV_Potential.units:~})'#(1/cm)' the ':~' gives the short form
        
        y_label = 'Current'
        yaxis_title = f'{y_label} ({self.CV_data_entries[0].CV_Current.units:~})'
        
        fig.update_layout(
            title=f'{y_label} over {x_label} - Cyclic Voltammetry',
            xaxis_title=xaxis_title,
            yaxis_title=yaxis_title,
            xaxis=dict(
                fixedrange=False,
            ),
            yaxis=dict(
                fixedrange=False,
            ),
            #legend=dict(yanchor='top', y=0.99, xanchor='left', x=0.01),
            template='plotly_white',
            showlegend=True,
            hovermode="closest", #"x unified",
            hoverdistance=10,
        )
        
        fig.update_xaxes(showspikes=True,)  # <-- add this line
        fig.update_yaxes(showspikes=True)  # <-- add this line
        
        # figures.append(
        #     PlotlyFigure(
        #         label=f'{y_label}-{x_label} linear plot',
        #         #index=0,
        #         figure=fig.to_plotly_json(),
        #     ),
        # )
        
        figure_json = fig.to_plotly_json()
        figure_json['config'] = {'staticPlot': False, 'displayModeBar': True, 'scrollZoom': True, 'responsive': True, 'displaylogo': True, 'dragmode': True}
        
        figures.append(
            PlotlyFigure(
                label=f'{y_label}-{x_label} linear plot',
                figure=figure_json
            )
        )
        
        self.figures = figures

        return figures
    
    def read_section(self, contentIDSlines, start_line, num_lines):
        section_lines = []
        #with open(file_path, 'r', errors='ignore') as file:
        #contentIDSlines = file_path.readlines()
        for current_line_number, line in enumerate(contentIDSlines, start=1):
            # Check if we are at the starting line
            if current_line_number >= start_line:
                #print(line)
                # Strip whitespace from the line
                stripped_line = line.strip()
                # Check if the line is empty
                if stripped_line == "":
                    break  # Stop if an empty line is encountered
                section_lines.append(stripped_line)  # Add the line to the list
                # Stop if we have read the specified number of lines
                if len(section_lines) >= num_lines:
                    break

        return section_lines
    
    
    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger'):
        """
        The normalize function of the `MeasurementRaman` section.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        """
        # super().normalize(archive, logger)
        try:
            #Check if there's any CV .ids file provided in main section
            if self.data_as_ids_file:
                if not self.data_as_ids_file.endswith('.ids'):
                    raise DataFileError(f"The file '{self.data_as_ids_file}' must have a .ids extension.")
                
                
                # Otherwise parse the file - ignore the iso8859-15 encoding
                with archive.m_context.raw_file(self.data_as_ids_file,'r', encoding='iso8859-15') as idsfile:
                    positions_startdate = [] # list of data entries position
                    # Load the data from the file
                    contentIDSlines = idsfile.readlines()  # Read all lines into a listidsfile.read()
                    
                    # Read the file line by line and search for 'primary_data'
                    for line_number, line in enumerate(contentIDSlines):
                        #start_index = 0
                        #while True:
                            # Find the next occurrence of the search string
                        found_data = line.find('starttime=')
                            #if found == -1:
                            #    break  # No more occurrences in this line
                            # Store the position as a tuple (line_number, character_position)
                        if found_data >= 0:
                            # first occurrence: start time and date of frame
                            # next line: end time and date of frame
                            positions_startdate.append((line_number, contentIDSlines[line_number], contentIDSlines[line_number+1]))  
                            #start_index += 1  # Move to the next character to continue searching
                            
                    #print(positions_startdate)
                    
                    # Convert Europe/Berlin to UTC
                    import pytz
                    from dateutil import parser as dataparser 
                    # dates:    DD.MM.YYYY HH:MM:SS in Berlin/Europe time zone
                    starttime = positions_startdate[1][1].strip().split("=")[1] # starttime=14.10.2022 16:42:50 -> 14.10.2022 16:42:50
                    exp_time_start = dataparser.parse(starttime, dayfirst=True)
                    
                    local_tz = pytz.timezone('Europe/Berlin')
                    target_tz = pytz.timezone('UTC')
                    
                    exp_time_start = local_tz.localize(exp_time_start) # set to Berlin time
                    exp_time_start = target_tz.normalize(exp_time_start) #transfer to UTC
                    
                    self.datetime = exp_time_start
                    
                    endtime = positions_startdate[len(positions_startdate)-1][2].strip().split("=")[1]
                    exp_time_end = dataparser.parse(endtime, dayfirst=True)
                    
                    exp_time_end = local_tz.localize(exp_time_end) # set to Berlin time
                    exp_time_end = target_tz.normalize(exp_time_end) #transfer to UTC
                    
                    self.datetime_end = exp_time_end
                
                ###
                # Find the 'Scanrate=' in .ids file
                # Find the 'Title=' in .ids file
                ###
                
                positions_scanrate_data = [] # list of data entries position of keyword 'Scanrate=' in Volt/second
                positions_title_data = [] # list of data entries position of keyword 'Title=' for every cycle
                
                # Otherwise parse the file - ignore the iso8859-15 encoding
                with archive.m_context.raw_file(self.data_as_ids_file,'r', encoding='iso8859-15') as idsfile:
                    # Load the data from the file
                    contentIDSlines = idsfile.readlines()  # Read all lines into a listidsfile.read()
                    
                    # Read the file line by line and search for 'primary_data'
                    for line_number, line in enumerate(contentIDSlines):
                        found_data_scanrate = line.find('Scanrate=')
                        found_data_title = line.find('Title=')
                        
                        # Important: the line starts (== 0) with the keyword
                        if found_data_scanrate == 0:
                            positions_scanrate_data.append((line_number, line.strip().split('=')[1]) )  
                        
                        if found_data_title == 0:
                            positions_title_data.append((line_number, line.strip().split('=')[1]) )  

                
                ###
                # Find the position of the data 
                ###
                
                positions_primary_data = [] # list of data entries position
                
                # Otherwise parse the file - ignore the iso8859-15 encoding
                with archive.m_context.raw_file(self.data_as_ids_file,'r', encoding='iso8859-15') as idsfile:
                    # Load the data from the file
                    contentIDSlines = idsfile.readlines()  # Read all lines into a listidsfile.read()
                    
                    # Read the file line by line and search for 'primary_data'
                    for line_number, line in enumerate(contentIDSlines):
                        #start_index = 0
                        #while True:
                            # Find the next occurrence of the search string
                        found_data = line.find('primary_data')
                            #if found == -1:
                            #    break  # No more occurrences in this line
                            # Store the position as a tuple (line_number, character_position)
                        if found_data >= 0:
                            positions_primary_data.append((line_number, int(contentIDSlines[line_number+1].strip('\x00')), int(contentIDSlines[line_number+2].strip()) ))  
                            #start_index += 1  # Move to the next character to continue searching
                        
                #print(positions_primary_data) # the first list is useless
                    
                with archive.m_context.raw_file(self.data_as_ids_file,'r', encoding='iso8859-15') as idsfile:
                    # Load the data from the file
                    contentIDSlines = idsfile.readlines()  # Read all lines into a listidsfile.read()
                    
                    numFrames = len(positions_primary_data)-1 # the first entry is useless
                    # Create subsection if not existing
                    if not self.CV_data_entries:
                        self.CV_data_entries = []
                        # Ensure the list is long enough
                        while len(self.CV_data_entries) < numFrames:
                            self.CV_data_entries.append(CVData())  # Append a placeholder value
                    
                    # Create new if not sufficient long enough - overwrites the default
                    if len(self.CV_data_entries) < numFrames:
                        self.CV_data_entries = []
                        while len(self.CV_data_entries) < numFrames:
                            self.CV_data_entries.append(CVData())  # Append a placeholder value

                    # Do this for every frame in file
                    for frame in range(1,numFrames+1,1): # omit the first entry and add the last
                        section_lines = self.read_section(contentIDSlines, positions_primary_data[frame][0]+4, positions_primary_data[frame][2])
                        
                        import numpy as np
                        dataxyfile = np.loadtxt(section_lines) # convert the section into data
                        
                        # Separate the columns into two variables and copy to 
                        self.CV_data_entries[frame-1].CV_Potential = ureg.Quantity(dataxyfile[:, 0], 'volt')
                        self.CV_data_entries[frame-1].CV_Current = ureg.Quantity(dataxyfile[:, 1], 'ampere')
                        
                        # Provide the Scanrate (in V/s) used in every run
                        self.CV_data_entries[frame-1].CV_Scanrate = ureg.Quantity(float(positions_scanrate_data[frame][1]), 'volt/second')
                        # Provide the Title of every measurement if not present
                        if self.CV_data_entries[frame-1].name is None:
                            self.CV_data_entries[frame-1].name = positions_title_data[frame][1]
                        
                    
            #Check if any file is provided in any subsection for .txt files
            for r_d_entries in self.CV_data_entries:
                if r_d_entries.data_as_txt_file:
                    # Check if the file has the correct extension: txt or plain 2-column txt
                    # if not r_d_entries.data_as_tvf_or_txt_file.endswith('.tvf') and not r_d_entries.data_as_tvf_or_txt_file.endswith('.txt'):
                    #     raise DataFileError(f"The file '{r_d_entries.data_as_tvf_or_txt_file}' must have a .tvf or .txt extension.")
                    
                    # Otherwise parse the file with *.txt - ignore the iso8859-15 encoding
                    #if r_d_entries.data_as_txt_file.endswith('.txt'):
                    with archive.m_context.raw_file(r_d_entries.data_as_txt_file,'r', errors='ignore') as xyfile:
                            # Load the data from the file
                            import numpy as np
                            dataxyfile = np.loadtxt(xyfile, skiprows=1)
                            
                            # Separate the columns into two variables and copy to 
                            r_d_entries.CV_Potential = ureg.Quantity(dataxyfile[:, 1], 'volt') # dataxydfile[:, 0]  # First column
                            r_d_entries.CV_Current = ureg.Quantity(dataxyfile[:, 2], 'ampere') #dataxydfile[:, 1]  # Second column
                    
                    
            
        except Exception as e:
            logger.error('Invalid file extension for parsing.', exc_info=e)
        
        if self.CV_data_entries:
            #Otherwise create plot
            self.figures = self.generate_plots()
        
        super().normalize(archive, logger)



#from nomad.datamodel.metainfo.eln import BasicEln # ElnWithStructureFile
#class OverviewClass(ElnWithStructureFile, Schema):
from nomad.datamodel.data import Schema
class CRC1415SampleOverview(BasicEln, ReadableIdentifiers, Schema): #EntryData, ArchiveSection):
#class CRC1415SampleOverview(ELNSubstance, ReadableIdentifiers, EntryData, ArchiveSection):

#import runschema.run
#class CRC1415SampleOverview(ReadableIdentifiers, EntryData, runschema.run.Run):
    '''
    Class autogenerated from yaml schema for ELNSubstance.
    '''
    m_def = Section(#validate=False,
        categories=[CRC1415Category],
        label='CRC1415-SampleOverview',
        a_eln={
            "lane_width": '600px',
            "properties": {
                "order": [
                    "tags",
                    "Project_Tags_Synthesis",
                    "Project_Tags_Characterization",
                    "Project_Tags_Theory",
                    "name",
                    "short_name",
                    "institute",
                    "owner",
                    "datetime",
                    "lab_id",
                    "data_as_cif_file",
                    "molecular_formula",
                    "substance_type",
                    "sample_is_from_collaboration",
                    "Sample_reference_from_collaboration",
                    "description",
                    "chemicals"
                ]
            }
        },
    )
    name = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
        default="Default Sample Name",
    )
    tags = Quantity(
        type=MEnum(['internal', 'collaboration', 'project', 'other']),
        a_eln={
            "component": "AutocompleteEditQuantity"
        },
        shape=["*"],
    )
        
    Project_Tags_Synthesis = Quantity(
        type=MEnum(['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A08', 'A10', 'A11']),
        a_eln={
            "component": "AutocompleteEditQuantity",
            "label": "A: Materials Synthesis",
        },
        shape=["*"],
        #a_elasticsearch=Elasticsearch(material_entry_type),
        # see nomad/nomad/datamodel/results.py
    )
    Project_Tags_Characterization = Quantity(
        type=MEnum(['B01', 'B04', 'B06', 'B07', 'B08', 'B09', 'B10', 'B11']),
        a_eln={
            "component": "AutocompleteEditQuantity",
            "label": "B: Characterization",
        },
        shape=["*"],
    )
    Project_Tags_Theory = Quantity(
        type=MEnum(['C01', 'C03', 'C04', 'C06', 'C07', 'C08', 'C09']),
        a_eln={
            "component": "AutocompleteEditQuantity",
            "label": "C: Theory",
        },
        shape=["*"],
    )
    
    data_as_cif_file = Quantity(
        type=str,
        description="A reference to an uploaded .cif file containing the 'Crystallographic Information File'.",
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
        
    chemicals = Quantity(
        type=CRC1415Chemical,
        a_eln={
            "component": "ReferenceEditQuantity"
        },
        shape=["*"],
    )
    substance_type = Quantity(
        type=MEnum(['crystalline solid', 'powder', 'solution', 'other']),
        a_eln={
            "component": "RadioEnumEditQuantity"
        },
    )
    sample_is_from_collaboration = Quantity(
        type=bool,
        a_eln={
            "component": "BoolEditQuantity"
        },
        default=False,
    )
    Sample_reference_from_collaboration = Quantity(
        type='CRC1415SampleOverview',
        description='If sample is received by collaboration, then reference it here.',
        a_eln={
            "component": "ReferenceEditQuantity"
        },
        shape=["*"],
    )
    
    molecular_formula = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
        )
    
    Other_reference_to_measurement = Quantity(
        type=ELNMeasurement,
        description='If sample is measure otherwise, then reference it here.',
        a_eln={
            "component": "ReferenceEditQuantity"
        },
        shape=["*"],
    )
    
    IR_Instrument = SubSection(
        section_def=IRInstrument,
        repeats=True,
    )
    Contributors = SubSection(
        section_def=Contributors,
        repeats=True,
    )
    
    Measurement_CV=SubSection(
       section_def=MeasurementCV,
       repeats=True,
    )
    
    Measurement_Adsorption=SubSection(
       section_def=MeasurementAdsorption,
       repeats=True,
    )
    
    Measurement_IR = SubSection(
        section_def=MeasurementIR,
        repeats=True,
    )
    
    Measurement_Raman =SubSection(
       section_def=MeasurementRaman,
       repeats=True,
    )
    
    Measurement_SEM = SubSection(
        section_def=MeasurementSEM,
        repeats=True,
    )
    
    Measurement_TEM =SubSection(
       section_def=MeasurementTEM,
       repeats=True,
    )
    
    Measurement_TGA =SubSection(
       section_def=MeasurementTGA,
       repeats=True,
    )
    
    Measurement_XRD = SubSection(
        section_def=MeasurementXRD,
        repeats=True,
    )
    
    # from crc1415plugin.schema_packages.MeasurementGeneric import MeasurementGeneric
    # from .schemas_measurement import MeasurementGeneric
    Measurement_Generic = SubSection(
        section_def=MeasurementGeneric,
        repeats=True,
    )
    

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
    #def normalize(self, archive, logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `CRC1415 Sample` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)
        
        
        try:
            #Check if there's any .cif file provided in main section
            if self.data_as_cif_file:
                if not self.data_as_cif_file.endswith('.cif'):
                    raise DataFileError(f"The file '{self.data_as_cif_file}' must have a .cif extension.")
                
                from ase.io import read

                from nomad.normalizing import normalizers
                from nomad.normalizing.results import ResultsNormalizer

                system_normalizer_cls = None
                for normalizer in normalizers:
                    if normalizer.__name__ == 'SystemNormalizer':
                        system_normalizer_cls = normalizer
                        break

                from nomad.datamodel.metainfo import runschema
                from nomad.normalizing.optimade import OptimadeNormalizer
                from nomad.atomutils import Formula
                from nomad.datamodel.results import Material, System
                from nomad.normalizing.common import nomad_atoms_from_ase_atoms
                from nomad.normalizing.topology import add_system_info, add_system

                with archive.m_context.raw_file(self.data_as_cif_file) as f:
                    try:
                        ase_atoms = read(f.name)
                    except Exception as e:
                        raise ValueError('could not read structure file') from e

                    if not archive.results.material:
                        archive.results.material = Material()
                        # extract molecular_formula out of cif file
                        self.molecular_formula = ase_atoms.get_chemical_formula()
                        formula = Formula(ase_atoms.get_chemical_formula())
                        formula.populate(archive.results.material)

                    # Create a System: this is a NOMAD specific data structure for storing structural
                    # and chemical information that is suitable for both experiments and simulations.
                    system = System(
                        atoms=nomad_atoms_from_ase_atoms(ase_atoms),
                        label='File:' + self.data_as_cif_file,
                        description='Structure read from the file.',
                        structural_type='bulk',
                        dimensionality='3D',
                    )

                    # archive.results.topology can used to represent relations between systems.
                    # E.g. "System A is part of System B". In our case there is only a single system.
                    topology = {}
                    add_system_info(system, topology)
                    add_system(system, topology)
                    archive.results.material.topology = list(topology.values())
                    

        except Exception as e:
            logger.error('Error exception during parsing/processing.', exc_info=e)
        
        from nomad.atomutils import Formula
        from nomad.datamodel.results import Material, System
        
        # # in case only molecular_formula is provided
        if self.molecular_formula and not self.data_as_cif_file:
            logger.warn(f'This overview page holds: {self.data_as_cif_file} with formula: {self.molecular_formula}')
            if not archive.results.material:
                archive.results.material = Material()
                formula = Formula(self.molecular_formula)
                formula.populate(archive.results.material)
            else:
                formula = Formula(self.molecular_formula)
                formula.populate(archive.results.material)
                



from nomad.datamodel.metainfo.plot import PlotSection, PlotlyFigure
from nomad.metainfo import Quantity, Section, SubSection, SchemaPackage
from nomad.metainfo.metainfo import SubSection, MEnum
import plotly.express as px
from nomad.datamodel.data import Schema

class MeasurementExample(PlotSection, Schema):
    '''
    Class with PlotSection also shown in OverviewClass.
    '''
    m_def = Section(
        a_eln={
            "overview": True,
        },
    )

    def normalize(self, archive, logger):
        # Otherwise create plot
        fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])

        self.figures = []
        self.figures.append(PlotlyFigure(label='Measurement Example:', figure=fig.to_plotly_json()))
        super().normalize(archive, logger)


class OverviewClass(Schema):
    '''
    Class for overview of measurement section.
    '''
    m_def = Section()

    Measurement_type = Quantity(
        type=MEnum(['NMR', 'XRD', 'other']),
        a_eln={
            "component": "RadioEnumEditQuantity"
        },
    )

    Measurement_Example = SubSection(
        section_def=MeasurementExample.m_def,
        repeats=True,
    )


m_package.__init_metainfo__()
