#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from typing import (
    TYPE_CHECKING,
)

from nomad.config import config

#from nomad.parsing.tabular import TableData
from nomad.datamodel.data import (
    ArchiveSection,
    AuthorReference,
    EntryData,
    EntryDataCategory,
    Schema,
)
from nomad.datamodel.metainfo.basesections.v1 import ReadableIdentifiers
from nomad.datamodel.metainfo.eln import (
    BasicEln,
    Chemical,
    ELNInstrument,
    ELNMeasurement,
)
from nomad.metainfo import (
    MEnum,
    Quantity,
    SchemaPackage,
    Section,
    SubSection,
)
from nomad.metainfo.metainfo import (
    Category,
)

# Release candidate
# Released Schemas
from .schemas_measurement import (
    MeasurementAdsorption,
    MeasurementCV,
    MeasurementGeneric,
    MeasurementImages,
    MeasurementIR,
    MeasurementRaman,
    MeasurementSEM,
    MeasurementTEM,
    MeasurementTGA,
    MeasurementXRD,
)

# from nomad.metainfo.elasticsearch_extension import (
#     Elasticsearch,
#     material_entry_type,
#     entry_type as es_entry_type,
#     create_searchable_quantity,
# )

if TYPE_CHECKING:
    from nomad.datamodel.datamodel import (
        EntryArchive,
    )
    from structlog.stdlib import (
        BoundLogger,
    )
    
configuration = config.get_plugin_entry_point(
    'crc1415plugin.schema_packages:CRC1415SampleOverview'
)



m_package = SchemaPackage(name='CRC1415 Sample ELN')


class DataFileError(Exception):
    """Custom exception for data file errors."""
    pass


class CRC1415Category(EntryDataCategory):
    """
    A category for all plugins defined in the `crc1415-plugin` plugin.
    """

    m_def = Category(label='CRC1415', categories=[EntryDataCategory])
    

class CRC1415CategoryMeasurement(EntryDataCategory):
    """
    A category for all plugins defined in the `crc1415-plugin` plugin.
    """

    m_def = Category(label='CRC1415-Measurement', categories=[EntryDataCategory])


class CRC1415CategoryUtility(EntryDataCategory):
    """
    A category for all plugins defined in the `crc1415-plugin` plugin.
    """

    m_def = Category(label='CRC1415-Utility', categories=[EntryDataCategory])
    


class CRC1415Chemical(Chemical, EntryData, ArchiveSection):
    '''
    This is an example description for Chemical.
    A description can contain **markdown** markup and TeX formulas, like $\\sum\\limits_{i=0}^{n}$.
    '''
    m_def = Section(
        categories=[CRC1415CategoryUtility],
        label='CRC1415-Chemical',
    )
    
    Reference_to_Chemical = Quantity(
        type='CRC1415Chemical',
        description='If a reference to another chemical is needed, then reference it here.',
        a_eln={
            "component": "ReferenceEditQuantity",
            "label": "Reference to Chemicals",
        },
        shape=["*"],
    )
    
    form = Quantity(
        type=MEnum(['crystalline solid', 'powder', 'solution']),
        a_eln={
            "component": "EnumEditQuantity"
        },
    )
    cas_number = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )
    ec_number = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `CRC1415Chemical` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


class CRC1415Instrument(ELNInstrument, EntryData, ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section(
              categories=[CRC1415CategoryUtility],
              label='CRC1415-Instrument',)
    
    Reference_to_Instrument = Quantity(
        type='CRC1415Instrument',
        description='If a reference to another instrument is needed, then reference it here.',
        a_eln={
            "component": "ReferenceEditQuantity",
            "label": "Reference to Instruments",
        },
        shape=["*"],
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Instrument` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


# class IRInstrument(Instrument, ArchiveSection):
#     '''
#     Class autogenerated from yaml schema.
#     '''
#     m_def = Section()


class Contributors(ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    Contributors = Quantity(
        type=AuthorReference,
        a_eln={
            "component": "AuthorEditQuantity"
        },
    )











#from nomad.datamodel.metainfo.eln import BasicEln # ElnWithStructureFile
#class OverviewClass(ElnWithStructureFile, Schema):
#from nomad.datamodel.data import Schema


class CRC1415SampleOverview(BasicEln, ReadableIdentifiers, Schema): #EntryData, ArchiveSection):
#class CRC1415SampleOverview(ELNSubstance, ReadableIdentifiers, EntryData, ArchiveSection):

#import runschema.run
#class CRC1415SampleOverview(ReadableIdentifiers, EntryData, runschema.run.Run):
    '''
    Class autogenerated from yaml schema for ELNSubstance.
    '''
    m_def = Section(#validate=False,
        categories=[CRC1415Category],
        label='CRC1415-SampleOverview',
        a_eln={
            "lane_width": '600px',
            "properties": {
                "order": [
                    "tags",
                    "Project_Tags_Synthesis",
                    "Project_Tags_Characterization",
                    "Project_Tags_Theory",
                    "name",
                    "short_name",
                    "institute",
                    "owner",
                    "datetime",
                    "lab_id",
                    "data_as_cif_file",
                    "molecular_formula",
                    "substance_type",
                    "sample_is_from_collaboration",
                    "Sample_reference_from_collaboration",
                    "description",
                    "Chemicals",
                    "Instruments",
                ]
            }
        },
    )
    name = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
        default="Default Sample Name",
    )
    tags = Quantity(
        type=MEnum(['internal', 'collaboration', 'project', 'other']),
        a_eln={
            "component": "AutocompleteEditQuantity"
        },
        shape=["*"],
    )
        
    Project_Tags_Synthesis = Quantity(
        type=MEnum(['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A08', 'A10', 'A11']),
        a_eln={
            "component": "AutocompleteEditQuantity",
            "label": "A: Materials Synthesis",
        },
        shape=["*"],
        #a_elasticsearch=Elasticsearch(material_entry_type),
        # see nomad/nomad/datamodel/results.py
    )
    Project_Tags_Characterization = Quantity(
        type=MEnum(['B01', 'B04', 'B06', 'B07', 'B08', 'B09', 'B10', 'B11']),
        a_eln={
            "component": "AutocompleteEditQuantity",
            "label": "B: Characterization",
        },
        shape=["*"],
    )
    Project_Tags_Theory = Quantity(
        type=MEnum(['C01', 'C03', 'C04', 'C06', 'C07', 'C08', 'C09']),
        a_eln={
            "component": "AutocompleteEditQuantity",
            "label": "C: Theory",
        },
        shape=["*"],
    )
    
    data_as_cif_file = Quantity(
        type=str,
        description="A reference to an uploaded .cif file containing the 'Crystallographic Information File'.",
        a_browser={
            "adaptor": "RawFileAdaptor"
        },
        a_eln={
            "component": "FileEditQuantity"
        },
    )
        
    # chemicals = Quantity(
    #     type=CRC1415Chemical,
    #     a_eln={
    #         "component": "ReferenceEditQuantity"
    #     },
    #     shape=["*"],
    # )
    substance_type = Quantity(
        type=MEnum(['crystalline solid', 'powder', 'solution', 'other']),
        a_eln={
            "component": "RadioEnumEditQuantity",
            "label": 'Sample condition'
        },
    )
    sample_is_from_collaboration = Quantity(
        type=bool,
        a_eln={
            "component": "BoolEditQuantity"
        },
        default=False,
    )
    Sample_reference_from_collaboration = Quantity(
        type='CRC1415SampleOverview',
        description='If sample is received by collaboration, then reference it here.',
        a_eln={
            "component": "ReferenceEditQuantity"
        },
        shape=["*"],
    )
    
    molecular_formula = Quantity(
        type=str,
        a_eln={
            "component": "StringEditQuantity"
        },
        )
    
    Other_reference_to_measurement = Quantity(
        type=ELNMeasurement,
        description='If sample is measure otherwise, then reference it here.',
        a_eln={
            "component": "ReferenceEditQuantity"
        },
        shape=["*"],
    )
    
    Chemicals = SubSection(
        section_def=CRC1415Chemical,
        repeats=True,
    )
    Instruments = SubSection(
        section_def=CRC1415Instrument,
        repeats=True,
    )
    Contributors = SubSection(
        section_def=Contributors,
        repeats=True,
    )
    
    Measurement_CV=SubSection(
       section_def=MeasurementCV,
       repeats=True,
    )
    
    Measurement_Adsorption=SubSection(
       section_def=MeasurementAdsorption,
       repeats=True,
    )
    
    Measurement_Images=SubSection(
       section_def=MeasurementImages,
       repeats=True,
    )
    
    Measurement_IR = SubSection(
        section_def=MeasurementIR,
        repeats=True,
    )
    
    Measurement_Raman =SubSection(
       section_def=MeasurementRaman,
       repeats=True,
    )
    
    Measurement_SEM = SubSection(
        section_def=MeasurementSEM,
        repeats=True,
    )
    
    Measurement_TEM =SubSection(
       section_def=MeasurementTEM,
       repeats=True,
    )
    
    Measurement_TGA =SubSection(
       section_def=MeasurementTGA,
       repeats=True,
    )
    
    Measurement_XRD = SubSection(
        section_def=MeasurementXRD,
        repeats=True,
    )
    
    # from crc1415plugin.schema_packages.MeasurementGeneric import MeasurementGeneric
    # from .schemas_measurement import MeasurementGeneric
    Measurement_Generic = SubSection(
        section_def=MeasurementGeneric,
        repeats=True,
    )
    

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
    #def normalize(self, archive, logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `CRC1415 Sample` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)
        
        
        try:
            #Check if there's any .cif file provided in main section
            if self.data_as_cif_file:
                if not self.data_as_cif_file.endswith('.cif'):
                    raise DataFileError(f"The file '{self.data_as_cif_file}' must have a .cif extension.")
                
                from ase.io import read
                from nomad.normalizing import normalizers

                system_normalizer_cls = None
                for normalizer in normalizers:
                    if normalizer.__name__ == 'SystemNormalizer':
                        system_normalizer_cls = normalizer
                        break

                from nomad.atomutils import Formula
                from nomad.datamodel.results import Material, System
                from nomad.normalizing.common import nomad_atoms_from_ase_atoms
                from nomad.normalizing.topology import add_system, add_system_info

                with archive.m_context.raw_file(self.data_as_cif_file) as f:
                    try:
                        ase_atoms = read(f.name)
                    except Exception as e:
                        raise ValueError('could not read structure file') from e

                    if not archive.results.material:
                        archive.results.material = Material()
                        # extract molecular_formula out of cif file
                        self.molecular_formula = ase_atoms.get_chemical_formula()
                        formula = Formula(ase_atoms.get_chemical_formula())
                        formula.populate(archive.results.material)

                    # Create a System: this is a NOMAD specific data structure for storing structural
                    # and chemical information that is suitable for both experiments and simulations.
                    system = System(
                        atoms=nomad_atoms_from_ase_atoms(ase_atoms),
                        label='File:' + self.data_as_cif_file,
                        description='Structure read from the file.',
                        structural_type='bulk',
                        dimensionality='3D',
                    )

                    # archive.results.topology can used to represent relations between systems.
                    # E.g. "System A is part of System B". In our case there is only a single system.
                    topology = {}
                    add_system_info(system, topology)
                    add_system(system, topology)
                    archive.results.material.topology = list(topology.values())
                    

        except Exception as e:
            logger.error('Error exception during parsing/processing.', exc_info=e)
        
        from nomad.atomutils import Formula
        from nomad.datamodel.results import Material, System
        
        # # in case only molecular_formula is provided
        if self.molecular_formula and not self.data_as_cif_file:
            logger.warn(f'This overview page holds: {self.data_as_cif_file} with formula: {self.molecular_formula}')
            if not archive.results.material:
                archive.results.material = Material()
                formula = Formula(self.molecular_formula)
                formula.populate(archive.results.material)
            else:
                formula = Formula(self.molecular_formula)
                formula.populate(archive.results.material)
                


# 
# from nomad.datamodel.metainfo.plot import PlotSection, PlotlyFigure
# from nomad.metainfo import Quantity, Section, SubSection, SchemaPackage
# from nomad.metainfo.metainfo import SubSection, MEnum
# import plotly.express as px
# from nomad.datamodel.data import Schema
# 
# class MeasurementExample(PlotSection, Schema):
#     '''
#     Class with PlotSection also shown in OverviewClass.
#     '''
#     m_def = Section(
#         a_eln={
#             "overview": True,
#         },
#     )
# 
#     def normalize(self, archive, logger):
#         # Otherwise create plot
#         fig = px.scatter(x=[0, 1, 2, 3, 4], y=[0, 1, 4, 9, 16])
# 
#         self.figures = []
#         self.figures.append(PlotlyFigure(label='Measurement Example:', figure=fig.to_plotly_json()))
#         super().normalize(archive, logger)
# 
# 
# class OverviewClass(Schema):
#     '''
#     Class for overview of measurement section.
#     '''
#     m_def = Section()
# 
#     Measurement_type = Quantity(
#         type=MEnum(['NMR', 'XRD', 'other']),
#         a_eln={
#             "component": "RadioEnumEditQuantity"
#         },
#     )
# 
#     Measurement_Example = SubSection(
#         section_def=MeasurementExample.m_def,
#         repeats=True,
#     )


m_package.__init_metainfo__()
